schema_version: 1

context:
  name: probeinterface
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/probeinterface-${{ version }}.tar.gz
  sha256: 600d0c213d53c94e4cb4fad851df8e65145e8a19c1a521e54cf32a9c2c6720c6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - numpy
    - packaging
    - requests

tests:
  - python:
      imports:
        - probeinterface
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Python package to handle probe layout, geometry and wiring to device.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/SpikeInterface/probeinterface
  repository: https://github.com/SpikeInterface/probeinterface
  documentation: https://probeinterface.readthedocs.io/

extra:
  recipe-maintainers:
    - dhmjhu
